version: '3.4'

services:
  bookfast-facility:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
    ports:
      - "30409:80"
    volumes:
      - ${OneDrive}/dev/BookFast/KeyVault:/root/.keyvault:ro

  bookfast-files:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
    ports:
      - "30410:80"
    volumes:
      - ${OneDrive}/dev/BookFast/KeyVault:/root/.keyvault:ro

  bookfast-booking:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
    ports:
      - "30411:80"
    volumes:
      - ${OneDrive}/dev/BookFast/KeyVault:/root/.keyvault:ro

  bookfast-search-indexer:
    environment:
      - DOTNET_ENVIRONMENT=Production
    volumes:
      - ${OneDrive}/dev/BookFast/KeyVault:/root/.keyvault:ro

  bookfast-search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
    ports:
      - "30412:80"
    volumes:
      - ${OneDrive}/dev/BookFast/KeyVault:/root/.keyvault:ro
      