services:
  bookfast.identity:
    image: ${DOCKER_REGISTRY-}bookfast-identity
    build:
      context: .
      dockerfile: src/Services/Identity/BookFast.Identity/Dockerfile
    ports:
      - 5001:8081

  bookfast.database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: bookfast.database
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - ./.containers/database/data:/var/opt/mssql/data
      - ./.containers/database/log:/var/opt/mssql/log
      - ./.containers/database/secrets:/var/opt/mssql/secrets
    ports:
      - "5433:1433"
