services:
  bookfast.identity:
    image: ${DOCKER_REGISTRY-}bookfast-identity
    container_name: identity
    build:
      context: .
      dockerfile: src/Services/Identity/BookFast.Identity/Dockerfile
    ports:
      - 5001:8081
    depends_on:
      - bookfast.database
      - bookfast.telemetry-dashboard

  bookfast.property-management:
    image: ${DOCKER_REGISTRY-}bookfast-property-management
    container_name: property-management
    build:
      context: .
      dockerfile: src/Services/PropertyManagement/BookFast.PropertyManagement/Dockerfile
    ports:
      - 5101:8081
    depends_on:
      - bookfast.database
      - bookfast.azurite
      - bookfast.telemetry-dashboard

  bookfast.database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - ./.containers/database/data:/var/opt/mssql/data
      - ./.containers/database/log:/var/opt/mssql/log
      - ./.containers/database/secrets:/var/opt/mssql/secrets
    ports:
      - "5433:1433"
      
  bookfast.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    command: azurite-blob --blobHost 0.0.0.0
    ports:
      - "10000:10000"
    volumes:
      - ./.containers/azurite:/data

  bookfast.telemetry-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: telemetry-dashboard
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18889:18889
      - 18888:18888