version: '3.4'

services:
  bookfast-facility:
    image: ${DOCKER_REGISTRY-}bookfast-facility
    build:
      context: .
      dockerfile: BookFast.Facility/Dockerfile

  bookfast-facility-rpc:
    image: ${DOCKER_REGISTRY-}bookfast-facility-rpc
    build:
      context: .
      dockerfile: BookFast.Facility.Rpc/Dockerfile

  bookfast-files:
    image: ${DOCKER_REGISTRY-}bookfast-files
    build:
      context: .
      dockerfile: BookFast.Files/Dockerfile
    depends_on:
      - bookfast-facility

  bookfast-booking:
    image: ${DOCKER_REGISTRY-}bookfast-booking
    build:
      context: .
      dockerfile: BookFast.Booking/Dockerfile
    depends_on:
      - bookfast-facility

  bookfast-search-indexer:
    image: ${DOCKER_REGISTRY-}bookfast-search-indexer
    build:
      context: .
      dockerfile: BookFast.Search.Indexer/Dockerfile
    depends_on:
      - bookfast-facility

  bookfast-search:
    image: ${DOCKER_REGISTRY-}bookfast-search
    build:
      context: .
      dockerfile: BookFast.Search/Dockerfile
      