apiVersion: v1
kind: Service
metadata:
  name: bookfast-files
  namespace: {{ default "bookfast-staging" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: bookfast-files
  type: ClusterIP