apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookfast
  namespace: {{ default "bookfast-staging" .Release.Namespace }}
#  annotations:
#    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: {{ .Values.dns.backend }}
      http:
        paths:
          - backend:
              service:
                name: bookfast-facility
                port:
                  number: 80
            path: /api/facilities
            pathType: Prefix
          - backend:
              service:
                name: bookfast-facility
                port:
                  number: 80
            path: /api/accommodations
            pathType: Prefix
          - backend:
              service:
                name: bookfast-booking
                port:
                  number: 80
            path: /api/bookings
            pathType: Prefix
          - backend:
              service:
                name: bookfast-search
                port:
                  number: 80
            path: /api/search
            pathType: Prefix
    - host: {{ .Values.dns.files }}
      http:
        paths:
          - backend:
              service:
                name: bookfast-files
                port:
                  number: 80
            path: /
            pathType: Prefix
 
# see https://stackoverflow.com/questions/64125048/get-error-unknown-field-servicename-in-io-k8s-api-networking-v1-ingressbacken
# see https://kubernetes.io/docs/concepts/services-networking/ingress/