<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Azure.Communication.Email" />
    <PackageReference Include="Fluid.Core" />
    <PackageReference Include="MassTransit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BookFast.Common.Application\BookFast.Common.Application.csproj" />
  </ItemGroup>
</Project>
