<Project Sdk="Microsoft.NET.Sdk">
    
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\BookFast.Common.Application\BookFast.Common.Application.csproj" />
  </ItemGroup>
    
</Project>
