name: Build production

# Controls when the action will run. 
on:
  # Triggers the workflow on the specific tag
  push:
    tags:
        - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
            
      # see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # see https://github.com/docker/login-action#github-container-registry
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Tag BookFast.Facility
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility:${{ env.RELEASE_VERSION }}
        
      - name: Tag BookFast.Facility.Rpc
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility-rpc:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility-rpc:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility-rpc:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-facility-rpc:${{ env.RELEASE_VERSION }}
        
      - name: Tag BookFast.Files
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-files:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-files:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-files:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-files:${{ env.RELEASE_VERSION }}
        
      - name: Tag BookFast.Booking
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-booking:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-booking:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-booking:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-booking:${{ env.RELEASE_VERSION }}
        
      - name: Tag BookFast.Search.Indexer
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search-indexer:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search-indexer:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search-indexer:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search-indexer:${{ env.RELEASE_VERSION }}
        
      - name: Tag BookFast.Search
        run: |
          docker pull ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search:latest
          docker tag ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search:latest ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search:${{ env.RELEASE_VERSION }}
          docker push ${{ secrets.REGISTRY_NAME }}/bookfast/bookfast-search:${{ env.RELEASE_VERSION }}
        