<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\BookFast.Common.Infrastructure\BookFast.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\BookFast.Booking.Application\BookFast.Booking.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BookFast.Booking.Tests" />
  </ItemGroup>
</Project>
